### ISSUE TITLE
frio: Post display doesn't reload after (un)ignoring it

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#7834]
Clicking on the `Ignore thread` link in the post menu works, but the display never reloads because of a Javascript error:

```
main.js:652 Uncaught TypeError: data.match is not a function
    at Object.success (main.js:652)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at z (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```

**Comment by MrPetovan** [comment]
Caused by #7762
